### PR TITLE
chore: very aggressive package upgrades for CLI tool

### PR DESCRIPTION
**Pull request by yjhuoh**
hi best friends,

this is yujay from trellisconnect. we are doing a security audit on our systems and our auditors flagged a large number of package vulnerabilities. i've been tracking them down across a few of our repos and a number of them are related to very outdated packages used in your CLI tool.

unfortunately i could not find any tests to validate that these packages didn't break anything. i checked the `inquirer` and the API seemed mostly the same despite two major versions 🤷‍♀️

produced below is the npm audit results run on your repo:
```
# Run  npm install inquirer@8.2.0  to resolve 2 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ inquirer                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ inquirer > strip-ansi > ansi-regex                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ inquirer                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ inquirer > string-width > strip-ansi > ansi-regex            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install update-notifier@5.1.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ update-notifier                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ update-notifier > boxen > ansi-align > string-width >        │
│               │ strip-ansi > ansi-regex                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘


# Run  npm install yargs@17.2.1  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution in yargs-parser                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ yargs                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ yargs > yargs-parser                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-p9pc-299p-vxgp            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ inquirer-fuzzy-path                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ inquirer-fuzzy-path > inquirer > string-width > strip-ansi > │
│               │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │  Inefficient Regular Expression Complexity in                │
│               │ chalk/ansi-regex                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ansi-regex                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ yurnalist                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ yurnalist > strip-ansi > ansi-regex                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-93q8-gq69-wqmw            │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

### CODE REVIEW

**Comment by yjhuoh** [comment]
should fix https://github.com/avohq/avo/issues/13 as well

**Comment by hugihlynsson** [comment]
Hi @yjhuoh and thanks for the PR! We'll be taking a look at the updated dependencies change-logs and make sure that they don't break anything so we can get these vulnerable dependencies out quickly ⏫⏫

**Comment by yjhuoh** [comment]
thanks @hugihlynsson

**Review by logason — APPROVED** [review]
Thank you for the contribution @yjhuoh 🙌 

We've verified that all breaking changes introduced in these updates should not impact our usage of them.

We'll release avo@1.8.0 after merging this PR.

LGTM!

**Comment by logason** [comment]
Hey @yjhuoh, just wanted to let you know that the changes introduced in this PR have now been released as part of `avo@1.8.0`. We've also released `avo@2.0.0` including some additional dependency updates that also required bumping the minimum required Node version from 6 to `^12.20.0 || ^14.13.1 || >=16.0.0`

**Pull request merged**
